---
driver:
  name: terraform
  directory: .

provisioner:
  name: terraform
  variables:
    project_id: "spheric-alcove-430818-f9"
    region: "us-central1"  # Change as needed

suites:
  - name: default
    run_list:
      - recipe[default]
    attributes:

